export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";

export const ADD_USER_REQUEST = "ADD_USER_REQUEST";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAIL = "ADD_USER_FAIL";

export const LIST_USERS_REQUEST = "LIST_USERS_REQUEST";
export const LIST_USERS_SUCCESS = "LIST_USERS_SUCCESS";
export const LIST_USERS_FAIL = "LIST_USERS_FAIL";

export const ADD_DBS_REQUEST = "ADD_DBS_REQUEST";
export const ADD_DBS_SUCCESS = "ADD_DBS_SUCCESS";
export const ADD_DBS_FAIL = "ADD_DBS_FAIL";

export const LIST_DBS_REQUEST = "LIST_DBS_REQUEST";
export const LIST_DBS_SUCCESS = "LIST_DBS_SUCCESS";
export const LIST_DBS_FAIL = "LIST_DBS_FAIL";

export const ADD_PLAYER_REQUEST = "ADD_PLAYER_REQUEST";
export const ADD_PLAYER_SUCCESS = "ADD_PLAYER_SUCCESS";
export const ADD_PLAYER_FAIL = "ADD_PLAYER_FAIL";

export const LIST_PLAYERS_REQUEST = "LIST_PLAYERS_REQUEST";
export const LIST_PLAYERS_SUCCESS = "LIST_PLAYERS_SUCCESS";
export const LIST_PLAYERS_FAIL = "LIST_PLAYERS_FAIL";
